### ISSUE TITLE
Methods are inverted

### ISSUE THREAD

**Issue by ldimitroff** [ubugnu/Arduino#2]
Hi there, I'm using your library, but seems that on my schema the methods are inverted:

The on_press and on_release I can't seem to find a way to properly use them, I need to invoke the function of the "onPressed" in the on_release event and the same thing with the on_press event. Same thing with the other events.

Am I using it wrong?
Thanks

**Comment by nazimboudeffa** [comment]
This project is collaborative in what sense ?
i mean do this library shared for any other objective, or is it totally free ? Even if i think that all what is on github is shared for strong convictions on mankind

**Comment by ghost** [comment]
thanks for asking, it's been a long time i didn't see ubu

**Comment by ubugnu** [comment]
@ldimitroff you should use the NBP (that is on_release) ALONE to handle a short (unique) button press, this is if you dont need to fire event when the button is pressed but only when it was released (the library, of course, cancels the potentiel bounces). Can you paste your code here?
@boudeffa asta3mlah kima t7ab
@deeegroovy ubu is pythonic now ;-)

**Comment by ldimitroff** [comment]
@ubugnu thanks for the quick reply, I understand what you say, but I need to fire two events, one when the button is pressed and one when the button is released. 
If I use the library as it is, the hardware button it's "inverted" the press is a release event and the other way around, the release is a press event... 
Let's say I want to turn on a LED the moment I press the button and turn if off when the button is released, I need to invert the methods: 
I should expect:

```
btnReset.on_press(turnLEDOn);
btnReset.on_release(turnLEDOff);
```

but have to do this instead:

```
btnReset.on_press(turnLEDOff);
btnReset.on_release(turnLEDOn);
```

**Comment by ubugnu** [comment]
@ldimitroff I think these are not the right methods for what you want to do, since `on_press` and `on_release` are devoted for short presses, try to use **LBsP** and **LBP** instead, normally (I don't have an arduino at hand!):
btnReset.on_long_press(turnLEDOn);
btnReset.on_long_release(turnLEDOff);
and tell me if it works.

**Comment by ldimitroff** [comment]
Hmmm I'm confused, cause I don't want to use the "long press" event, since I want detect the press right away (and not to wait for the gap to happen), I can use the "long release" instead, in order to detect when  the release was from a "long press"...

**Comment by ubugnu** [comment]
I said that because of your example (Let's say I want to turn on a LED the moment I press the button and turn if off when the button is released), if you tell me precisely what you want to do perhaps I can help better then that

**Comment by ubugnu** [comment]
No answer, I close the issue.
